version: '2'

services:

  migrate:
    image: docker.citr.ous.ca/iohint-celery-worker:latest
    depends_on:
      - iohint-rabbitmq
      - iohint-pgsql
    environment:
      SECRET_KEY: my-secret-key
      DATABASE_URL: postgres://iohint@iohint-pgsql:5432/iohint
      CELERY_BROKER_URL: amqp://guest:guest@iohint-rabbitmq:5672//
    command: ['./manage.py', 'migrate']

  django-shell:
    image: docker.citr.ous.ca/iohint-celery-worker:latest
    depends_on:
      - iohint-rabbitmq
      - iohint-pgsql
    environment:
      SECRET_KEY: my-secret-key
      DATABASE_URL: postgres://iohint@iohint-pgsql:5432/iohint
      CELERY_BROKER_URL: amqp://guest:guest@iohint-rabbitmq:5672//
    command: ['./manage.py', 'shell']

  psql:
    image: postgres:9.6
    depends_on:
      - iohint-pgsql
    command: ['psql', '-h', 'iohint-pgsql', '-U', 'iohint', 'iohint']
